### PR TITLE
Environment removal

### PR DESCRIPTION
**Pull request by udhayacommits**
Remove references to Environment where it is not used #444

Please verify. I am removing tests that are referencing `Environment`

### CODE REVIEW

**Comment by udhayacommits** [comment]
@trickeydan , Removed changes in files other than tests/test_stack.py

**Comment by trickeydan** [comment]
Blocked on #458

**Comment by trickeydan** [comment]
Blocked due to *yet another* bug in our CI on forks :(

The good news is that the build does pass when I run it manually! :)

Thanks @udhayacommits I'll try and get #460 resolved ASAP and then we should be able to merge. We really appreciate the contribution :smile:

**Comment by trickeydan** [comment]
Merged manually, overriding CI because #460 was delayed.

Thanks for your contibution @udhayacommits!

**Pull request merged**
