### PR TITLE
Set master as the default parent branch

### LINKED ISSUE #430: Master is failing tests
This appears to be due to the `CIRCLE_PULL_REQUEST` variable not being set.

Introduced in #413

### PR DESCRIPTION
**Pull request by trickeydan**
Fixes #430

### CODE REVIEW

**Comment by trickeydan** [comment]
https://wiki.bash-hackers.org/syntax/pe

**Comment by kierdavis** [comment]
If the pull request env var isn't set, is the merge-with-parent-branch
check even needed?

**Comment by trickeydan** [comment]
> If the pull request env var isn't set, is the merge-with-parent-branch check even needed?

Good point. I think that is a better solution

**Comment by kierdavis** [comment]
> Good point. I think that is a better solution

--> #440

**Comment by trickeydan** [comment]
Closed in favour of #440

**Pull request closed without merging**
