### PR TITLE
Add CI job for Python 3.8

### PR DESCRIPTION
**Pull request by kierdavis**
While we don't formally support Python 3.8 yet, this will help us
catch any potential incompatibilities ahead of time.

Currently the build fails due to an upstream issue in numpy: https://github.com/numpy/numpy/issues/14403

### CODE REVIEW

**Comment by trickeydan** [comment]
This is another case where doing #97 would be useful.

**Comment by trickeydan** [comment]
#402 will probably help with this, as I don't think `j5` is specifically dependent on numpy.

**Comment by trickeydan** [comment]
>  don't think `j5` is specifically dependent on numpy.

We currently depend on PyQuaternion, which depends on numpy.

Thoughts on factoring out vision into a separate module also? It doesn't feel and never has felt like it should be part of the core library.

**Comment by trickeydan** [comment]
The upstream issue has been fixed. I suspect they will release the fix within the next two weeks.

**Comment by trickeydan** [comment]
Numpy has updated.

**Comment by kierdavis** [comment]
I have a feeling that `opencv-contrib-python` isn't available for Python 3.8 and would need to be removed, but it's hard for me to be sure because of #352. Tempted to just see what happens when this hits master and the CI actually gets to run.

**Comment by trickeydan** [comment]
I'm going to merge and see what happens. I'm prepared to remove `opencv-contrib-python` from the dev deps as it shouldn't be there anyway.

#363

**Comment by trickeydan** [comment]
Please see #443

**Pull request merged**
