### PR TITLE
fixed Issue 196

### PR DESCRIPTION
**Pull request by Shivam60**
Fixed 'Using type() instead of isinstance() for a typecheck.' issue in tests\backends\hardware\test_env.py

### CODE REVIEW

**Comment by trickeydan** [comment]
Unfortunately there was a misconfiguration in CircleCI, which has now been fixed. However, it has been unable to detect your branch and I have been unable to trigger it manually.

Possible fixes:
1) You might be able to trigger the build manually using the CircleCI API. [See here](https://circleci.com/docs/2.0/api-job-trigger/)
2) Another commit can be pushed to this branch.
3) You can amend your current commit to change the commit hash, and then force push that new commit to your branch.

Any questions / help let us know :)

**Comment by kierdavis** [comment]
> 2\. Another commit can be pushed to this branch

I'd recommend creating an empty commit, like so: https://coderwall.com/p/vkdekq/git-commit-allow-empty

**Comment by Shivam60** [comment]
I did create an empty commit, https://github.com/Shivam60/j5/commit/1977a4ee3331107ff1daac04736f91941ab81258
but now I am lost as to what to do.

**Comment by trickeydan** [comment]
Hi,
CircleCI has run the tests against your code and it has failed linting.

The error message is: `tests/backends/hardware/test_env.py:9:42: E231 missing whitespace after ','`

You can view the error yourself by clicking on the little red cross next to the commit.

> I cant create a pull request from that commit.

No need. GitHub is clever.

**Pull request merged**
