### PR TITLE
Clean up setup.py

### LINKED ISSUE #135: setup.py includes tests in packages
The current setup.py includes `tests`.

Two options:

- Exclude tests in the `find_packages` call
- Define our packages and not use `find_packages`

### PR DESCRIPTION
**Pull request by trickeydan**
Resolves #135.

Also in light of #95, I have updated the author name and email.

### CODE REVIEW

**Comment by kierdavis** [comment]
Not sure if I'm testing this right, but it looks like `setup.py install` still installs everything in the `tests` directory.

```
$ python -m virtualenv ve
$ ve/bin/python setup.py install
$ unzip -t ve/lib/python3.6/site-packages/j5-0.0.2-py3.6.egg
...
    testing: tests/__init__.py        OK
    testing: tests/test_smoke.py      OK
    testing: tests/test_stack.py      OK
...
```

Also note that #93 introduces a "tests_hw" directory that probably would want to be ignored too.

**Comment by trickeydan** [comment]
Interesting. I got this from the [setuptools docs](https://setuptools.readthedocs.io/en/latest/setuptools.html#id10) and I'm pretty sure I'm using it correctly.

**Comment by kierdavis** [comment]
What difference should I expect to be seeing with this change, then?

**Comment by trickeydan** [comment]
I would expect to not see the `tests` included in the distributions.

**Comment by kierdavis** [comment]
Please fix the merge conflicts before I test this.

**Comment by Skybound1** [comment]
This isn't really required anymore due to the removal of `setup.py`

**Comment by trickeydan** [comment]
Superseded by #163

**Pull request closed without merging**
