### PR TITLE
Consolidate j5 version

### PR DESCRIPTION
**Pull request by trickeydan**
I have created a `j5.VERSION` that is used for docs and packaging. Additionally, this could be used in code to have different behaviour if we need to do so.

### CODE REVIEW

**Comment by sedders123** [comment]
Should this be `__version__` or are we not following [PEP 396](https://www.python.org/dev/peps/pep-0396/)? (Not saying we have to, just wondering if there was a reason)

**Comment by trickeydan** [comment]
I was not aware of PEP 396. I will update this.

**Comment by trickeydan** [comment]
Also note: resolves #80

**Comment by trickeydan** [comment]
This is now failing on a lack of Type Defininitions for `packaging`. Any suggestions on how we solve this? I'm not sure if we really should bother making a `.pyi` for it, somewhat out of scope.

**Comment by kierdavis** [comment]
We could add a hint to ignore typing on the offending import.

However, is `packaging.Version` necessary, especially since we immediately convert back to a string? Unless I'm missing something it doesn't seem like introducing a new dependency for this is justified.

**Comment by trickeydan** [comment]
> We could add a hint to ignore typing on the offending import.
> 
> However, is `packaging.Version` necessary, especially since we immediately convert back to a string? Unless I'm missing something it doesn't seem like introducing a new dependency for this is justified.

I made use of `packaging.Version` as it ensures that the version are compatible for PEP440 and it's a requirement of `setuptools` anyway. I'm happy to remove this if you'd like. It also make it possible to dynamically find the short version number that Sphinx wants.

**Comment by kierdavis** [comment]
I can see the benefit if the `Version` object was exposed directly, but if the only purpose is validating the string then that might as well be done once by a human during code review rather than every time the library is loaded. I don't feel that strongly about it though, you're welcome to keep it (so long as the typing gets fixed).

**Comment by trickeydan** [comment]
I think I'm probably in favour of removing it now, especially considering that the types on it are broken.

**Pull request merged**
