### PR TITLE
Serial number refactor

### PR DESCRIPTION
**Pull request by kierdavis**
WORK IN PROGRESS, EXPECT FORCE PUSHES

### CODE REVIEW

**Comment by trickeydan** [comment]
This is quite major. We'll have to think carefully about shipping this change.

**Comment by kierdavis** [comment]
I don't expect this to get reviewed or deployed until after the summer school

**Comment by trickeydan** [comment]
(We should use the draft functionality over WIPbot)

**Comment by kierdavis** [comment]
* I can't remember what the goal of this was.
* It's unlikely to ever get finished.
* The master branch has been developing for five months since this branch was forked off, there's almost certainly going to be a lot of conflicts if/when we try to merge.

I'm going to close this off - we can pick it up later if it turns out this refactor is actually necessary.

**Pull request closed without merging**
