### PR TITLE
Finish vision constructs

### PR DESCRIPTION
**Pull request by trickeydan**
Finishing off the initial vision data constructs. 

Orientation is deliberately excluded at this point, as it is not a MUST for a shippable vision system.

### CODE REVIEW

**Comment by trickeydan** [comment]
I've done a merge from master into this branch. Ignore any commits before 
efc21ab

**Comment by RealOrangeOne** [comment]
This PR is almost impossible to review, as there's so many other unrelated commits in the diff. Can we get the unrelated commits removed from the branch, or just wait until the other branches are merged?

**Comment by trickeydan** [comment]
I'm unable to get that diff nice, so I think the best approach will be to merge this into `vision` without review, and then review the diff into `master`. This approach will also prevent duplicated comments on these rather big changes.

**Comment by trickeydan** [comment]
I'm messaging @HU90m directly to inform him that I'm pushing to his branch as that would generally not be considered best practice.

**Pull request merged**
